### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by RhythmMark** [DigBullTech-viewer/ctf_web#89]
**在网页版**
1.怎么创建中文名命名的文件夹？
2.怎么重命名文件夹？
3.怎么更新fork的版本库？

**Comment by blackhater1** [comment]
恭喜你自己找到了答案👍
https://camo.githubusercontent.com/bcfe0a9f31ebccf6711d79955c2d4be2fc6efad2/687474703a2f2f692e737461636b2e696d6775722e636f6d2f6e335767332e676966

**Comment by RhythmMark** [comment]
不不不，重命名文件夹还不会，不知道有没有这个功能

**Comment by blackhater1** [comment]
这个网页版操作我也不会。。。
程序稍微大点，修改的地方复杂点，就无法通过网页来完成了，最好使用命令行哈
